# Generated by Django 4.0.5 on 2022-07-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interprete', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('año', models.DateField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
